// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Api.DataAccess;

namespace Products.Api.DataAccess.Migrations
{
    [DbContext(typeof(ProductsDBContext))]
    partial class ProductsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Products.Api.DataAccess.Contracts.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Products.Api.DataAccess.Contracts.Entities.RateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<decimal>("Rate");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Products.Api.DataAccess.Contracts.Entities.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount");

                    b.Property<Guid>("Id_product");

                    b.Property<Guid>("Id_rate");

                    b.HasKey("Id");

                    b.HasIndex("Id_product");

                    b.HasIndex("Id_rate");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Products.Api.DataAccess.Contracts.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Products.Api.DataAccess.Contracts.Entities.ProductEntity", "Product")
                        .WithMany("Transaction")
                        .HasForeignKey("Id_product")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Products.Api.DataAccess.Contracts.Entities.RateEntity", "Rate")
                        .WithMany("Transaction")
                        .HasForeignKey("Id_rate")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
